apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:ZqFvtoqjXhffrifCTsSBWZM9CM3jfeIyLgvhrcGRKUt2hFM55TOcb/2qA+R+YPs9fLSnqMOw409ZoAqAQ2BS2t8=,iv:73UB+nRWegXxg6uT7Pb+x5GJEvukGYSyEbZDo90nDi0=,tag:D4oVkaQ+lmwtnVxQHmtUlg==,type:comment]
    #ENC[AES256_GCM,data:vgJtwaPJMXmJnZq5mHu1XTCrtBSy6c74OCKXpdbxURM6m04+efwEpdQFmJk=,iv:uOH5fwlnhWI6St1Ek6gKv+j+0wFWGHsxcBVK/H2Ou5Q=,tag:SEOg5fjBTIv3jN+WoWqKPg==,type:comment]
    VIP: ENC[AES256_GCM,data:ZzLmqagowUIJhA==,iv:xAQ/jtZh558FY5OFHSDBkjzTiITTIHZlX0aAJMOKv5E=,tag:g8fT41nX39YdSyKcnes6WQ==,type:str]
    #ENC[AES256_GCM,data:e4HYA7aPxe8Yz/zVz/B6UU9rZUXoDPGf3vw=,iv:JkbxTPPnueHROjNj5UFGXq3QYwitnnF9kNtwinqeh/E=,tag:ImPlSLfy4Zvv6sxZkurY/g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:SmsA/Vcf898zSA==,iv:XZbJxWUeYpVpsH8bSByK4qJMRX7tgh5KzlNQueldNW8=,tag:Jw23uuEKZE8c/iRhPs/YSQ==,type:str]
    #ENC[AES256_GCM,data:ZobscHhDlFcW1R7kPhoYl3ctIsm5V+Ib4z/Jt8q/hKYyAA==,iv:ZXHiP1gX6PbjXl98I5wtQa4rj9c+6JcDGVl5WPI+dY0=,tag:X7CzTXr3BGkCC/cX/RAW1A==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:/ia+rKM4z5E=,iv:66rOQKR8F7LMyjNbF6jh+/SL9thsx3MEiGB/D1fPa8I=,tag:L3Ja3u17fW3aErICB8p1QQ==,type:str]
    #ENC[AES256_GCM,data:zDSJxbfjwfd/Gl8tEU9gKjh3zAUZFYE7rMQ22jEeKtP8m892OkfDDoKki6dfDvE=,iv:E7wtakIYOIFdRx6u4kMKja65koO6+4Idabz21w7af3k=,tag:LMvSwsAQ9UNcv3U213YKWg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:czwe3og2UM2AUrQhcOrw69k+SuRo,iv:6iRuZjnHCE8naO4WmFfJB/bU0kw+d52wjHt32QqiEbk=,tag:1FjXZ57LGO9g3zIZIQhh5A==,type:str]
    #ENC[AES256_GCM,data:bj0976Atf6MouX+uMpWXT6AFPamgpXcxNM0J9HKlXpK0te8th5SaLb/1yJdlPy3kyyJF4GzOcZ7Ras3+g/4y/pdmNcQFjiqDn6kW50zQ8Wo=,iv:NZm6sxBM6uOQuhN/Htq2PtApEMcyLwf9FtzYwUErnn0=,tag:Cuj86lm0eRbAxjbs006cAg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:qAexy5NhKRrzSw==,iv:74eKgBqx7nGbeGzU0Bb2nE8Ug6LwY2yCq76aQ4ATSxQ=,tag:7xSove1QJ/o2bVGT5j9T3Q==,type:str]
    #ENC[AES256_GCM,data:w8g+sMgoJ8/VE8fWBo5iQpMAeNuNl+XUf4Mmy6jBghTTWtIB4dhNMGza2FgSQwuc8faXv2kRH3A=,iv:9J//v8XlCDVFiJDXZ+qfgkAscjny31piEBVvpE8OWUQ=,tag:lbJDzQqtfb/3lVyHbPbQXQ==,type:comment]
    #ENC[AES256_GCM,data:cWZ/gNKKIorjG/Xv4vOIdKRK1PbienbvFA==,iv:kQuKrzOMM8vfU5F+nSuFANO+XlNmx92tEvhnBIUOb1w=,tag:E3qmlvcw5/t8qU4EsHT8mA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:SZw16sVMOetk1xUi+wica/C4NNEBYiP31RtfdmfpFpkCtk9ZaA03,iv:jsmweAuO6MlocCJa0L1ctNEhQNqW6PywmIKvvGSSDQ8=,tag:uheA0agHiQukw6BtD3Ju5w==,type:str]
    #ENC[AES256_GCM,data:KjqjxtIBHhYJlcBGszV6H4TcTndn8BGdOIP5tmjIr3Z+OQLHk0ayX1E1qgybDQR7E7YIdwbyZwUqzXXAzVlJyh/IiZfyGlE=,iv:5TyfWu06d4VSIGBGdtaZ/F+Z5ijMzJr7qcxK9IUm4X4=,tag:tZ8nyPtqG6OtdhUoP2344g==,type:comment]
    #ENC[AES256_GCM,data:Y33LONcjx7hRZvGD1km/PklLUDxuNax0msj7HRW72yQDb5R9BU8qKPfCiDBLcpQOOrJglnd1,iv:Ds39no8MM2ti0nxLJCStMFet6Bh1RCmBx5bw69zujlI=,tag:f3vyzSTrgH2bMmq943RaxA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:oSMqzlUb2BEza6EeBiWiyyj5O/LuHlNPcPwwf8wzLTs=,iv:LEpwGo1BTQfiPEK6OXPuATJGpUU1L8ma87YOQbwjLLo=,tag:3c+YJo6nGK1cP68X6G9SMQ==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:fV1atR1d8f9o5ZrQ,iv:gcHSDLcDhugfJtyAzsXBMZJJ2O6eDj9qhmlCwTwxyEU=,tag:gGbSIfcpPxpcq2e5fqac8w==,type:str]
    #ENC[AES256_GCM,data:zyISXh599LM=,iv:wDlrWrQf65i23f93WZgoGW6XvbwEhEdF3XGHuzyfAlM=,tag:tc7vv/eoLXrxV+z9N502CQ==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:gtJ7y3ist1OF1cl/ng==,iv:Rqp2qzwWt6+c9Gn5eFI5z9AEbZ8wiFyrLrp0ZE760pY=,tag:eBmIuChtR3DoBbbe5J9g2Q==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:bS65KXJ6Qyj2Dg==,iv:XT89isLo1SF75/FL0mvH9oxGG3qKGpQxYmTI1C/2r0U=,tag:cHvSzsEqQzMmZtSBiavPSw==,type:str]
    #ENC[AES256_GCM,data:ejRNKkRKKHqSlv38dAY=,iv:cGUM0NHJ0Tt5uftkrYT5+GsXl3FhUmwQZCKUAkOMRec=,tag:hmqpI0eSUuomJLNpWphRIg==,type:comment]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vvySAtoiyptpgIzfAAxcv1KxYS0/K7hIVQ==,iv:vP/EQbZ+TL8d//s1O4F9O7BBuvosOYD3UoIUGuhFeFI=,tag:3lsHla465QuxtnQZ1HncJQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:QEPuSnYzd4Q4yiesmQ/aySFuSjvydrFq5MsJigW1PBLZrwIJ4hg+FA==,iv:kOh75E8GBk1m0O5FUDKZaSoyOR36xKpMxDeiBlk3lvs=,tag:thKCW3/G0vnVpwN/T+YJxg==,type:str]
    #ENC[AES256_GCM,data:0bHTwB/783MO1pfuIg==,iv:qGBTqFc3PgZYPoMR2zwfDFWDaHo1B8XqV4xXN0NmtHY=,tag:3ndVWf/1xQ8pyojxTHQfAQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:+BrKTWluWj2jL+kXhg==,iv:T/bkD7qhxm7wbr5TaM6SclwO1quYJhZChT0AzLM7V8c=,tag:iCi60DnF9VVPUkbOeeHvIw==,type:str]
    SVCNET: ENC[AES256_GCM,data:oCBKdQjL77sKrZOXOA==,iv:I9b6ehb6sbFnIkDtq0Jz8zAYzJFVX5VvC80MHTOs+JI=,tag:ZaVKTL3fAs1UGYrM6echEg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:aqS5IA==,iv:VttygacUVTAhIOYUA8USNV20lM2wA69TT91k3JyHRW0=,tag:7KAzVthg4J+DGE+3GW8FBw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUHFoNThGdVhpRzZqRURZ
            UDF1Z2FwdVpsd0pFb0RzKzUzUEZiL2N5NGpjCnVXUi9IUVUxK1psMWladWJMTytY
            YU9jRFBobmxpRXJoVjRUNFpuVXl3Q2cKLS0tIHp4cENJVnVkNmZBa2hXS25pWDVD
            VFVQNHJxNzByTHVFUDg3K0lYMng3M1UK1lq+PVf7c9XvbmukFt6aLUCQIyyyJbsP
            dhVNswJqwvTigPHhYwIYi2AbnGdbZQV/bFbvtrVIPshEexEEj6SWIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T07:12:49Z"
    mac: ENC[AES256_GCM,data:LvVWxt34MmCpTPZaQT7MLxvLMvKEkW93lTTr/rdj3HJD7JgFeQbuI0sIwVr29G4IC2fyROuYS5Ec/ue2H3H1gDBLjtrGDaEEiSKZKTOHssp2rjrTlCmgKhjeDZmtosd2wWjvjvOQr1/l9AjSZiUon/BxUBIRme3XEeDd0DBQ2kA=,iv:yYnbIGYAtESgX+XUJMQgXc0MkpJa+TVuXAEuYu0NHsE=,tag:xHsvZR3YcjNRCA2CT49nsw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
