apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:pV+PP6GKX6odxJIsfpxDSpNtDt1gWBV0TzonInHH5boARpp4O7gh3TiNmaejfbwSd4lAjMJCFHeYsDEhnjlkJpw=,iv:23m5FzKkje4RQonOz1aKF/hGnTxO6XyoYAJDBdwh1cQ=,tag:hToTVVSLmX6AXOpWEcK8Yg==,type:comment]
    #ENC[AES256_GCM,data:VhByes6dojKXbxrdtrfE2z3FA6m5Sbr4L2zkDz1kyQquc6KQBruWIcCf3jo=,iv:YL4ZRvamNunUcvdXDm3ub0KewmZGkknsZbSApyFANJg=,tag:owMtGx4TOZMzJ7xt2G57WQ==,type:comment]
    VIP: ENC[AES256_GCM,data:fOLurqkO8DLyeQ==,iv:Li/IOHNujQkmF8ojHO+C0AEGuesYrQXn2qf7/3sOKaM=,tag:sEgcRkbeqdMLLn1ySTgTwg==,type:str]
    #ENC[AES256_GCM,data:EldWC8nS18GhanKwVKhs3E73qjJWbBpzijI=,iv:31COrYCdyuTg8HQqRBKgJeCdy+V1trgGOGuKQZDaYgI=,tag:L0tMoNjqtzgBeJAAlxUnRg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:HG1C6ZQefpLogA==,iv:6rbBxXiwuhKSItf+N3GnbIQZqCkKmtDE46p4FtmBP8A=,tag:vdIdm2K7G7dJ0unlt5C0Aw==,type:str]
    #ENC[AES256_GCM,data:oTOZHvxzpLaunrUxCW6lcgQER6I7+/RL+2SeB52dFid4hQ==,iv:hG9/m+mwWaMhPmLyACJjtWtLyDu+CCxVf2m+PGGowd0=,tag:R+NdubxXWD05hW8PyR40ww==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:rgMuslxdn1E=,iv:qt04n6vL8tmjU2Uf0dMIjZLWmJGrzqksVvz85iSsX3U=,tag:LSpQqunyHJqgQVLs323CwQ==,type:str]
    #ENC[AES256_GCM,data:/VvqD7zeJ4rZvnOqkIx9OpZqnBNbZ0UFbmYk3sz8B5o+oLNwujy1+fEGtY6YMPw=,iv:7gJdwNHUnxnRg3X0j1hyk07m4bx2KiGMcIryDOD8104=,tag:By2Om/XPDepFyJ+6Mxa26Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:RhTz5vkuS0PMohbK1acS7JdczMSY,iv:1PCW7FaxRnUyfBHKGoNP6h7t6g5HW9SDZCZMF2i8BmM=,tag:lfUqEx6VaWLE6c7In7OF/A==,type:str]
    #ENC[AES256_GCM,data:3Y0LZNJowE4rlijYI0iOf9R77wY8D7dH5f0yotubfSZpSVaYpt8vReYrh8Np4gUG5YM1T/BF77KNTK3NfL8EYZcf/9XYeIurRAeyqa0SETA=,iv:LNdsmKbKL5gc1K8itDku1kV1RbqTWSETDqNoN1Hz9Ow=,tag:Ol9UvhSfgEOobq+dbGlGDw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:ue8uRslwyCmGuQ==,iv:xS5bMdygpAR+X0iohYX/kmx4O22Bbf8AIgIXDwddV8I=,tag:RF4oadHPESptuW5xKYHFow==,type:str]
    #ENC[AES256_GCM,data:97osD2e+u7QOB2ImwQ2i4ixx8U3FwkdpjG+7fRkoosa1CIIj0ol04nq3vSVtmbEGQQre63js1Zk=,iv:B/XrcB8ek9OlHOfkCsz3dcJfiR5QNS6kK84uQSKSY9Q=,tag:wcxbiLRTQxBLAXoOFNZXLQ==,type:comment]
    #ENC[AES256_GCM,data:hrbB5z3kRVNEQwB0ZC76cZzxS2bhTtFCQw==,iv:bvstL3Cpl5Shr+S9+fBzFTECWgSByjr2J2xPcWWi9jg=,tag:O+p69rfiiA9PhEYuESkH6g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2qm7Cn6cc1KPNWYEuwA1RRDvJ5jtiRQdlDmB5NUlmYvAP+zrk+1j,iv:rvWxPu909xKx2TQtU/F3GSiK85qd1gTR+SMUfC0EtG8=,tag:hiQsL9oOnXyVlsoOax8vgg==,type:str]
    #ENC[AES256_GCM,data:I1aON5ygC49CDwUPGL/5ndv8PTAlbgcLed6m0OpHj/4bntYR/KuLLsMRTsFTpSMb0kedrz83nL2R2kB0byCHaFQhse8mcnA=,iv:MzX8p+DoipECUyJh1gF3Cmww6sqFcEIb+WoeNk9grEI=,tag:sMvqFxPD6ip1R1QvPX5Duw==,type:comment]
    #ENC[AES256_GCM,data:ln8yUH7IOauhnmqIwMz8kIhW8FaWDfFp8DK7/DY6DFJBEdeBvwo2zhujSB+5esyKhnIlrrw5,iv:orPFuS/mhBiX0PrFK5sq9EwllV5GorSqRe9xk5b7eU0=,tag:aF+4eBZY5HDSZgrc+xRrBw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:oVu69t9jovHc302wGJj2b4Z9iKT/op5ddG9DPyWnQrk=,iv:5a/+wCf4tOmVNJxG8Qkoom1ZfsfOPZENIvwOJPKhRsg=,tag:CjXjMIlDkoeuoFsf5v2CKg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:0BaKFiGq33GZjUKu,iv:sVu0VrO37HUNbp/kWd27WgUCAwbEEAPFwDZ0J7WJ8z4=,tag:p/o+etrFAw2R4GEPvMGL3g==,type:str]
    #ENC[AES256_GCM,data:ZcMiu6PWu5Q=,iv:jy0moVQ7G1DUGhZUTPwwNf87e2n51cXp4LWtmhPNVgE=,tag:GIJzGWNer7uXE3WUozdbFA==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:blfta4ueI79j3oNq6Q==,iv:4QyqEd0Q/rtM6/GYH9HtyYqfq2WbZaMubzAigG0/JtM=,tag:nHyLIvmGC7NR8IjAajG50w==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:aA5VzXRqlJ/3TQ==,iv:XbcNTv/P1qqKDTvFfqGyDN5ivB4a7x3gVyO/0ZOIre4=,tag:u3xcGulQyS09I8LbaafFLA==,type:str]
    #ENC[AES256_GCM,data:hlf+f2vRS2iRUoqq5Os=,iv:QAkkSORXoLEufTMQTQ8qctjkQZ5gmAWpM43dfnc6PME=,tag:+G07f4YkAh70To72FLo2eQ==,type:comment]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:BSx5SsZy/vbrcNnKJvi2pLXzlFjvGTHeCg==,iv:avO7UKK3yrQ/b5OEsvgluvUbk+yzE1k5RJVm21Eo0c4=,tag:f89lramEPRjo6ae7U2+3Pw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:y1yoUwIBEn4mpZVUyRZko2vtFFRgOFQ86VmxaGTlcW4qDxFiP5F/3g==,iv:ylteBJDibXJnC9K9uPayhD+i40Le3EQsB5YkmATHoy0=,tag:qh+IdyRIwVZqfJOy4GTYeQ==,type:str]
    #ENC[AES256_GCM,data:Rj2EvMtF/mekHOUtxw==,iv:30E4lQHkObNeUATFQrV0fr2NNbfD1Wqsgh7CQE07/tE=,tag:8xUxRj1GJcUIu0sQMlnBRA==,type:comment]
    PODNET: ENC[AES256_GCM,data:tmfrClxQAsbWU4/0Bw==,iv:LjyAdVxPyhNaxsC2t+V/QoYC19utJiBNZpLbsza07hA=,tag:E8Ank/9EuXYf2+hUieerQA==,type:str]
    SVCNET: ENC[AES256_GCM,data:zO56/uowzZugvmTNtQ==,iv:x3xGPlQpiEvgbFo7F3IQPzjMiuYLMhQiT2qqDYMXyOg=,tag:RAPQv9ej04bMTV76A5hr6Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:e+Amiw==,iv:tK1PTDkDmp8KvqVvDd+FW1rXxTVdDyHoYbuw0nC3Iw4=,tag:BYddEmuuGb3mdT1CFTkbiA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU2d4cHczd2xzSzFwcTlQ
            NERLMm92Z2pmSy9RUC9NTWI4ZXgvSHFLc0RzCndmOGdGUU5QMThhWmRMQ2c1cGJq
            VFNYbThHK1Vhc2lkVVk2djlEN0hPTlkKLS0tIGtjUjhqazVybVhOQ3NWWU5GUnhH
            SmR4alhOTnY1UUhsTW5KY0NTUGdITTgKc6lxxbpq3FrQlrltjvtoK7EaYxlB/YS1
            Wj9hfjJ9XEIl4Jpy8JBAkAkypcBl2c6wtEVECrwW0DieUSHY17uHsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T22:32:13Z"
    mac: ENC[AES256_GCM,data:Zgba1s3sLUW7dUDcwxaFZufyJIW5w5OPkaQwWKM+eRxQsmCyd6Nvb5e9Q0lUqRha/PefwWz4Hd9wyaCTmA+wMG9E/HPxcb5VyldSEWjCv178ymqsMo5BU06y5is78tnLTK8UL9w9keBT9C98vzi57oXqRSNLIiaoLa1K89NBLTY=,iv:yplgFEEYHnRc7g9/OxB8eCmyf18I8Ul1YR3051hgMi4=,tag:H/7cOd8LtaI2vHVLQU/BgA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
