apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:NLP8dvtjAw9LQirU6jiU1n1ruGFdopWzl8iPjkUs7M6Y1hXvCDrJnWBQilMkUVhbscCExV63k/9p90tDl+9Dra8=,iv:ngau5zjAN2g61EZD/Xbhn4g+M8sQuXqOZiOgkIqe5Pk=,tag:ok7oXnio+dm0hoMovDjpiQ==,type:comment]
    #ENC[AES256_GCM,data:2g96OmEzvbVWXiCurMbJ4r7w4djiHMFj2SY1Wy4tWFolLNARiG/zqosNbZc=,iv:NGtJ4DgpHqP6OhnAA5u7fAVWLIhsWjIwrKzHlAIA/iE=,tag:RTmGEQwtkVmoKBzcJ6s1/w==,type:comment]
    VIP: ENC[AES256_GCM,data:gL6yY7NvkhdRtA==,iv:isowhHGoCiKuiGtLoHlig3L583PnEEQaIE210SRY1C8=,tag:R1TeqHsYArqxe0z40OPA/Q==,type:str]
    #ENC[AES256_GCM,data:F+sKiDn1JvNJWlMbJvIlIU1TFGTdvgKSh6A=,iv:6t2spSRh9/tVPgh4PiowHwg3pUS7M7RUfQYNGi2cxJM=,tag:GgLkoCjsKzQIxrMEaZ8ntQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:isTw0VvQH0/rKg==,iv:lsFt0+ubvf2pEQPwtGu4GHK9x/TfCLqAeaC8kg1H5RI=,tag:UYNvm8ykhHBElcXwSCu95A==,type:str]
    #ENC[AES256_GCM,data:AbfTgU+3pGyPvXk7Ao4aeVKO4cX1aXQzx+UVYPVy9oNBRQ==,iv:5KO9r0fsOr7Y9qcRRY1KTXL56W8bjvUvE+DGrjEwsJI=,tag:E6wPJbGl7Hl+gjGvFt3jAA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gYe3Dwb6hso=,iv:XgsoJpdufpFo/2Fh3E9bYti3aKVbQ8I3YXtlhtKeR5A=,tag:v5vc0uW7T1rtIAUWz4MYEg==,type:str]
    #ENC[AES256_GCM,data:L7Tkn6uBI9BUuFexb3xDQDn2OSf8Vh5PEA4ZStEFnpwAardOcmFLk/AxWRIbAc8=,iv:BvvmFnsfjB7xc2igkjriCQDYSc4QxPMO5uXuVoL9RN4=,tag:du7itdNnrL+yrDWwwaqAOg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:gCD6W0i+mkeT5UC8eOe6H7lFobng,iv:59SugVlieUmqgwAaQ0mqlB1FB27ypPLsxoR+T2gYy1Q=,tag:cPkm2K6OqhCPEq/YBzrchQ==,type:str]
    #ENC[AES256_GCM,data:3Qn2M9dLBflIi4dGMrcT9MwLfSretCjPSgY8uQdNz/yQrOCz/yM0qDKEwnGp093LEcCJkJzwbNO9mp9kUC7+qlEBvui6LAemjKOhO347d+k=,iv:DVjKsIoJcJVrIzlcgLGfSi6iSGb0gTmtbm6IUu/GG0M=,tag:vCHmG47S6css4AakB0ELaw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:24crXThLYwMrIw==,iv:7lnpcZT0kh5gkVicYXqIbTGFeSLbftk2NIaGr0O8lSA=,tag:vonAWdDWJM1R4EB4dfSEyA==,type:str]
    #ENC[AES256_GCM,data:aHeNLIh9pjj6my1gTd/V+Lxj4nlPybUute9IukcV6gl6O9tgfYYQye3+GuGBUSzlTPswLef+ucE=,iv:jm99EJHWef8xCK1rHluS3mwYXvtf8onrjzwR70dbdv0=,tag:sUzfaJh+22MC8h5RgLjXoA==,type:comment]
    #ENC[AES256_GCM,data:rDZxLG0hJ7pN7J7c+MZR8V0pskB9BoidrQ==,iv:Pr4J9MTRe5ZxFl+kCf9L2CCqo+WsbaWAiGHT08jPxfw=,tag:70jAVvkqRHgSq5VdkDuAcg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:IROwzZbs6TwmLnOD6Ctr94BavcVA1+KokzP8vlvEGqSWn4fYqyn4,iv:mCoPkox4sZ3sP2RAyubFXLO9I1sd/cIXAtPWjYpE3us=,tag:ZfTFzPcGi4KqrZD7NTZwHg==,type:str]
    #ENC[AES256_GCM,data:Dxyi+Gt7vNloFlz130P8gvQwpV5HpAJIMvHOP73Iq18G7innlhRpo1SVCkHNorrdG6IW2FYrFiEwqADkfOHllK531YDn2I0=,iv:c7pAsYavHhxd2+JzyomZg49PQJSkz7OXzhqq+g/MDEE=,tag:TW/YMk7nIGZ0bZKyQA0tNQ==,type:comment]
    #ENC[AES256_GCM,data:eZhAWrfg36o4115lQgJ2WuL39NVXu7Fzlu2sqR/Ffo6ew+goW38Hfr/z2EZP4BBW+NBfYnLJ,iv:2+SwFQ3mhxiglweVlk/LAE3CdaUUJGmufWOEvzNMTE8=,tag:9K330xTUuonMg6yacACzlw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:v9mq1hQ/49XM/rOvlp5PODUgljDILkvjYprseIOyiPA=,iv:j6czreAQsqi6wnukPzcjQGcwbqLtwjWuU8u51PJjPGk=,tag:ITGD27Tvo/AzzIfGPRehnw==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:F08rwXGri6dVJXY1,iv:R6J8mz1x+TG2O0WCtoaKR4o8JYWyTYmIeQmFaO3nEAY=,tag:MnJbMYR6HVZ2mr8lIWR6kQ==,type:str]
    #ENC[AES256_GCM,data:KMCphpsgYno=,iv:gmszSB60o4YqC80OB1tmpraqmbybK/WndwcVPO/VMKQ=,tag:CjdG8Y70xfsJUtEJ0T3FLg==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:cyrp7wlcQexX5drDmQ==,iv:9O9KOQFO5/N/vRKO9CkwdTm96N/XhJ9NOGmH3CvtJWQ=,tag:6U2fCLW8MV78LeiunC/b/A==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Ia5zIpyYVPX9vw==,iv:1tlyZ8c0WCtDuvUuMJI5rfXvAteOtSYPSeKM7Fk3PCs=,tag:0gQqACLnvqkdAxF9Wy9iCw==,type:str]
    #ENC[AES256_GCM,data:vB3qrixtlKoOXHk5X9M=,iv:3eSCkKhxlGkGpHfG2E9bm7bo5ZYg2Smwh8H7k1kh4EQ=,tag:lVoRGls7tryg/JUfVBa6DQ==,type:comment]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:k9PAqzom8pJ3Q/c02Y9t7LYVJj6n8vlhJA==,iv:gREHB/rB2arHRkaCv5k4ZAgTMCslZNvA6F6G7HV/tPQ=,tag:njmjs2vzxS3aNgw7e5MlaA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:iQ4FOVP+RolJGR68AvI+HxCS6btN7b3Afy8RcKqKAxxcblTDBZNobg==,iv:fjAPysp/8ikyxbLz62XH9xAKsLQJNqD94hsKMIBFSsw=,tag:QYM1Huhyshr8XX3F3x/sLw==,type:str]
    #ENC[AES256_GCM,data:Ow2LKxCC69aD2SUGIw==,iv:6z1+0pAprcewEoapp5h8QWKYligYntUKXGILZRAxvZc=,tag:fkJhihspjP7Oea9X5Q3wAA==,type:comment]
    PODNET: ENC[AES256_GCM,data:igKygwLN2W5MNBUN+Q==,iv:HFACU81QMXUeWR9hzcIpXBdce5tYURNWwO9sbiaP/9Q=,tag:vHBzv5JO48mGYKqvdkcRuQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:svzVzLVIsbk+U9QGAw==,iv:KoiQDgq9S1FTz8St9FjENw4wVlKfJJbyab+aQTR/jXg=,tag:YmG0qoFB9PJOPgAkxsm6mw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:5mt2dw==,iv:Fp3TdWil/46OE4riTFKnNaRk6JzUazo/t0LS/qMxOxo=,tag:5LiU3/ib/cy9bJ6eCtZMHg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRjBTSHowTUdXOXE2QTZL
            RkU1eVdqQlpnWk5CUWU0Q1ZPM3BFYWNEMFZ3ClUrRmZ0TXViQ05HdTZuU1N3L0M1
            Yk5PUnlBUklKaVAzdVZ6SlQwSC9CTW8KLS0tIEdVZHZOd3RLclg3dkdFM0FaUlMz
            Y3lLL2M4NXhBRFhiYkJFbTlvMW42dXcK+hvP+s4bvps8j3AsuymHru+fnAWD1ThX
            wokK+9HxiltQZSmPqUr/Qt2dWRHfHsNM0FhsdTH+gHtbG+TNaMt/WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T23:18:55Z"
    mac: ENC[AES256_GCM,data:wg/60IbJdsI39dQ208Na61irX/i4M9a9U2I4R68MuIun7JVdKer79kbvviY3OMAm9/y0tYtzKY9lsKqjxm/CPjwmeahh5cGICgaUWsJT7eZGVX6h6Ea3DhSlmGx16qt55e9OZMFkmuwwU1VLstwOoBBXhJQufIy/iQ563GugiI0=,iv:TbiW1UoBvpMaiD948ywOW/AICUayA6US/J8bTJu9PWA=,tag:a/qIWLFjLeUGFSVsvL+3SA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
