apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KRWsLa9oxyEi9ktvrytCdZz1+o/LgNWVJEaw2LX7BbFGykW9pYTQqUy/FPHheIRAY9G0Duisc5ajk/wulmMCYcZXINvHmleTOMHBABz+zQZI3f0F4eRvDPp0vq3WRhXF4RxZOf/CSOd7v/A55g6VEJh+XOvul0Cs/BTYukZTfkbMILK0TsLlsGwAKCR4eWVMDQcr1ZIZ8trf0ObBDT92v2K1JwULxQbuKrEFxzjwS4GTRyk3WkepvfSgHWtVyiQKfF7dZSW3vxPfundd2EtmiaXeliPEUSwYrivR3dC5QYsGL4t8QIxMWMpfg5VeSYY3CbJts0B0BwFMA58oHiI59NRSuZyO5zWxCLGk24ubuhY/D3dr14zqL4HYJXqafv7+,iv:C/UbqTvDSH4mPoVMd8UqPpCHs0NqoPfrMOfjJRiJ878=,tag:hhrKRhToZHsaY5eUhgjrjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:0By1v+BdyaodEDp0vsjoBi/RKUfhJztsE361+o0izj1Xqx3bfVMTR/PDzyb1NaVXt+RbJvGD0wTRwPi3Z1rOLYvLfQ+W4mpiFfMQb0AiCJv/Rc3qFSlvVBmaMaLCWC06d8YHF2mmG/CTobmWvwx2uGuGrU8rxKT7DSUjImEEivXb4AnCgl9WOCWNvgQTTIpDwd4DJF3GyTL7BA87GdGrVoXlbG8ykYXUfsZv10ecoXqUH5hZHgO93RIl3JnlIELJ4thAiUEMuVuAd9SipQ==,iv:qk4SwJehyuaKz+VGiE1TZ0id8zmmj6D45PVFn+IJIaY=,tag:dnVu3tqsAC8fpi0ZfWZlrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:I6j6c1UhKEsxNKQr+6G5DR3edvA1ScBvN27kBYF0MbUyxc6qEMNPg/RGK2QSfnJzOMuIs8xwcENvF+JYEolRWiOkwojc/SuXXAXZqUxvvsLjG/I45ndcuK78CwLGwlZNKWuVNNkUIbKFK4DhXb+RZm4hRkPIiyZIAECrpVdUoB07m3rGGP0YcBDvyAU0570f0x0gTMnwJaHhH/EmL977UeEP2NUZYdRpkigY,iv:P+o2hiM2tbhOin5Nwd4rIKEi9mV2o7bTk5PSP4HzkYg=,tag:xX2STkAW3AzHfjElxrCAlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraXVCRlNjd1NqaWlHSUcr
            VHVEUDdVN2RWUjVBcXJub3Q4OGF0djd3a3pJCnpjZGRGZXFFKy9HVEVJNGJGc1Ba
            ZklKS0hvdC9lZlFTRHpndCtVV09jSEEKLS0tIHk5ZThaQmNYUkhqYWJkWUlFN2s0
            alBNWjQvelhwanZEVjJyZi82R1VreDAKCqYlIowyofWyTru3D97LWMRjmijC2Dqg
            uwOaIUmOuo6N3sIEIodDaiQGKqvqKRgD7kWf9caqfslAgGuBkXKZMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T23:02:33Z"
    mac: ENC[AES256_GCM,data:rGBC6pEgDj212e7Hd/oYHMqGAQznABeeuXbcQeG9ae7JLohMxyuFdyrNfo9Ldnqm+wnSMSzu9YdcSS8xW6f1tLc7f1E3uQx1ELa1ZpwVsMJQcrzLyWvM6C/0ZwKiF7WTfma2tFBS0MoTRupl8w1BZYQNsFeJiDXNiSUsCNlA8Vc=,iv:SGkTdtf6mB6I0sL6c0ekk0LOC/gj7yrwMvK87/Q5Jrg=,tag:hXSlrJEML61khpsW3w59AQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
