apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nC9EP/BqV2/AsMlpEMtAPdgElc/ChYSYtPEIOWAP+/0Dihwh+L1EvzoKFZ79I2I4xgaQNm9gGCrmmqMzTWWPDu2nRWVpQIWL8VZJF6fFd/3yV0o/BHZyDIxGwzFz+JFv1dixvgUoDISQ3euowFOyNjcnk7vcnRPBI+S6kf0/juXGkqqbbShXYnopiWTH41OpS2FcRJjHRGq2kOvMO85KId6khyUdF6MKjp/3B3jK4OmKCHEa2qpyesaiZQiUvNsWfS6MfdIVupcnvy18Izg5FKt4tZHFdlyU7yeM3Xnauzca08A2ysKzKLcV/+Fu/nfJYoP1jzvEPLqUueXjxdin70rDNcoB5BOUz5eF1blV4I7CvRKdMrlVvdmcL7cm4pem,iv:hUlcK3U6DHGxsIlW2QZYHXYWnrnUMt8qdp830wo8xSk=,tag:tHXC2JiiZjIUuZCu1g5FPw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ENzgg3tnPO7ZNmsuww+NwmlwCC6DoDds92wAzVb5Jx7Q7FPqTvWRs42ds734pdnZZCMweQMJ+JOGnVnj3lxIkKkGwT4Pzp19rZZ6Hn1X3K5yvwQUlxGE8uBtPXkhWZGToX87Gk0dsYIP+yPNbTmpd2R2ZXxzjcPxEvNBdB7cD5pa87zoOYZKH38MeG3rUuhZz3GGP+OCvV/f5OC1j93eA4ORnc0J5qzAuXSvsVCOtPh2oF3EmqDm3HZ/7+Gk6Zg/PVAWZj6SvzfHH3boUw==,iv:cSvE2yBWc8nHpuH/r189Gpo8EcF9LdGRVwyMyRXEGiI=,tag:HeZ99UxfVdaBXT+mkuW4mQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:KE1JXbhjUXsxaDfyPqvB0ILLxwW1+Wzh3jmf9SBcGb982V2xRHQxMASe8PIZ1hGs5CaMZP22kcYe1Lkn0QYNt+QC9OR72fPKGlFVaW8uj9qAyA6lZpAR3JO3R051qti2wDdTTCxAw3TbNojC9uoUHURQKy7MB6fFOkAnZaUyesnVFpt9xbo+xur/JPYApCsKgXjMOj+oPKT0KFb3LAn/HAGVAQkpyFXXGEQF,iv:PL3HjKcO0l/2J1GXwDVBJIopo04PF2HC4mdc5G1ImtM=,tag:WSNBNerNJcM20JEqqQQ6Dg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ1l2YVBuS1gxdVAwcFVP
            WDY5N2N5bEI0eEJCZDFlcW9NNTU1MXRqS3lnClVZcjB0VjdwRjRrMzZ6V004bVVD
            dXpQcWVyemtlc3pyTnByejFIRERKMlEKLS0tIEJPNzZib1RoTmtXSGZQQlQ2Mzdk
            ZzNXODE3RFdWTUNSZi9XTk5QdnEwd28KV1DWohJUw9cji72L8HOmx/Le6xw8iziO
            hahS6H4JjSJ2thjgluuFs4R2xVV7LjleUc7nIEYVTlMFKcEDNhQVHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T07:51:36Z"
    mac: ENC[AES256_GCM,data:mnk4Fq8NsGmrpg/2A0J6Lx2pKG3jqYBG38znGtwSgwWmf9L6TuBHeoVuxFO3Qf7fzM166WZQTOCXb7o2W624bahZ+b2PikdpqqP1HPgRRu4yc8lLFHWlqjzWK/jPMa1ufUO5NRaroEY8UGhoXPCwvizxVQTtioWUMCGH6C7mOr0=,iv:rl0NYnVybw1Y6qbWHyUO+eOnjaA0M9PMMjShlHsMTtg=,tag:HzAJH/daGv3tKvMA4J5zLA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
