apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VEFqfuIxTMYezv2jjJr7e2B9PCekSJ2GEGuTqmwMAoyoqu+Jgq7WP6TXhlp67UI4jhGZcKjADBMXVZ5U3Rv+SprT+EQnsRi4Jd0PxSQOjQGZpeAYertt0cqVqLzmBPpz4Syc/qG0SJ9k1ZXB7Flz58XrVLn2BKvnYTxSv8T+hNQ50PY512O7LbeLxVg3CmFXlYGew4MOzdkZFV3Dl3ZwX2KxxS4shu81PGjnkiMN0CzRoaDtYLhxE1Ppt+5Unxk9K+yTlGDtAKT9RzSRVHWSoaFMC3alTD/DA95HmKa68xoLpddvlltcba80a14BAp0y2KjZtK0xJzF2n/rI2WfQVCWsFW+tmEYz/7MUE9WRtPff+43rd6OcPPy2fPi+Bq+S,iv:T8tfzxz1n1WMnS5wWOwbbuuGz4c7hlKCRv6satKQ3uw=,tag:ykRFQ3whOhoKAq7ZVjpSfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:wADt9nIvMD1InxlkxJTYXEU3LTN05FG3RdUmh+xovuLtsEHWr42y8ZMew85DApu7G0V/nDBL3IGIQhMnm98D7FhX9h6ENrbcRweOpBkfT16uAEi+RsFit6spshoBV2QSrp5NvJXbuoJy773t0trABDp19mLEYcNE2Cdx9YWzLV2Jj3/T4UOIM/cf3RFYsKv5Raghchtt3f033qg4KPUeGA19VrpReYJ1Yj9g8I6D6VDmQ8fUIeD4B4auGj7+vsd1N742GTb65CmJ09Bk+A==,iv:zKTFPkWffnROifN51RGdttWncle/Ix5JdeYxB8KtJks=,tag:jtGpneRCIIYipOtoe6uUYQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:92JSwvCcefCaIzJUL/Iq/S1Kj6KBv/y4qmnB4PeYiGpmOYmy0tPAlZeRmqwgQqcmqg7QAb1B9m+IbewnbqoC25vXC6ReucMJF6Q4TuPK+8TV1O4dgrB/zFDzW4Bl+pshS6lO7tP6uixCd2KbUlfX29yPlvgXi9J3Tig8JANXKDfmtdRdqQ+1l77UOUilRJ25pGdfvBW7fX60x1YeuN6XCQPRQG+1tks5eNCy,iv:wFdUVMpXFMRvWqjoli4Ry9+emN0mkhTUd8lGy6JbZqM=,tag:Vb78aYo1hpKWRguYCxsuvQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdytscXdyVU9vNGs1VWlY
            RUNvVjhEd2lyUUt0TGZhKytqL1dIUzJHSEg4CnV0MUw1UTNGdXUvWExMaCtaVk5E
            L1BkUitnZElkRGx4NUxIRzJQWmpKRXcKLS0tIC9GZUdac2s2cktGTThnK1I4dTk3
            MGl4ZVJWbk9oT1BQZDZPaVAwckdMYVUKjclh29FI/g1SL5VIfDvn4h6SgoDWFuKj
            E8wGTiE6RBm8S2rcaRuhEfUFdqE0wPloLz6yvl4Bgpwz9zrZAauAkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T08:00:32Z"
    mac: ENC[AES256_GCM,data:XLlGuhisI2h31dcLqpMrQJE7Pe3bkhSjOSrv+ZhHtM+WM0+1JAfL+tQ8H4HbKUMlthD6iIbkzkKupXBNUjmhlZd5CA75+SpPoaMXPsNZh1BhZvpGr8Rb3VQKxQspSR3qYBSY+4VbQJU17FUC3eVhVpKFVRquEHTDT2O5iuH2CYY=,iv:Oq07D6XyLoCC6w6jq6y07j04xXVQ8nAgqU09ygVXpTo=,tag:s4/c55f5dEHWAX2EDmKeHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
