apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PYO+v691q2m+EZmhcey5NjzexK0Mou+EIcCz0c6w8NbUzBPsotKvGCxxDVoFKWpoo0FMngzKrZfZZ7rr0l2enzHSEVNTs0PgLy2ldoY8PY/mFH9AeN5rdcW8jwbmC14MnFhca/tnG3UxABSpN11o3/BHaK64KLsGQbAygF6LE5aipVnb318bM/1LH9X/asxq5gxbQqHLy7AyBY2tLQzF0YdVglgWbJMpcyF/OgUylkFXXbsOrHek0lZbOZbGRLZmIH45SLFUQc6KPlSvLww8uh1TWJKW9UTbbfk4v8Otv2EuaNPxgl4K+0lMqgjHyiCj3Qj5MkSBgPSozOIcOWuBSUOnaAlODtogO92/RlE1diMm2wA4ZRuMvpyD2bUdzgpC,iv:jKKjA16tiPUHs7657XPcbGp4J3AJZnhy9BoY3QWh4TA=,tag:cSp/ibau/plRKWrg7LSxxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Dm9zcm0MZnF85ALR0g3NZ5qvGKIGwe7GFnXI8CihHMuVD/87hl5uxTzutGkdQZ+B8hzmhEeM11I66jqkNOqWmiK0FUAa0bu1bj4dHOZQAs7x7xEtsuEajNy2GfZePDHBmpeScD4tFlCi3BQ1m1aeNIPAzFWr/LRjjwdKmC6TGA570zVMzr95ZjSoE2u9BkIvFLU4BXH8OlZ4DneVTmjkDJDO7E/jWDLoKLdInG4MTUlDBFT5vimQp8sD8hpL0aW6mEJ2DsP636A7nEgzHw==,iv:EUG1YR5kdjRmwX3D34+079x3FQX+0QnYkd3T4sDAex4=,tag:IuASAjqadaZdjbzU+ox4bg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wnr0sJuSgKNA61GvAyV9tqyzjc8riKCsA7dKr4jwe/OoeNF2wEpykPZrgERLQnu/savMFCsTUszrPkMwH2V8I844BzeFYHfPS/+SRfUpQsAFXjwTYASK90rcIoZYbaSdg9qNtSALTaF4+DYzmoma1lIkMh0c5LEThn1q62vcImWebX0q8w0NK1bMNWc+Sl6QSDYyx/1ObpolS5bx6uJ3yxt3b77SXG1cO+MY,iv:KUE7EcVd+Xyp16B9hSOriu0zkHdc7tPa9HG6anmmcVo=,tag:T0ipWj3XAlfNivLTQn/JBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WXoyYnUxb0JkSkFWUTE2
            MWZzR0l1MkVkcGpCUE9pOGs2cjk0bThHb1QwCnN4RkhCZ0NOQ0lhZUorY1Y5c3NG
            Ty9laW9lU215cTdacEFGZlRyMTZOWDQKLS0tIC84SjgxZ1YyV25NL0JEQTNaSzRT
            M1Y2QzFsUzhuaGcvSnkyOGZPQ1pjTFEKtO6PREPv3JHBl6ZpqEYVoEIVaY5BkjE7
            mUawvapNplW2IV738uDWsXDyeBWiK7U9m78ENZLYvYtq15aD8Y1huw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T07:37:43Z"
    mac: ENC[AES256_GCM,data:eO6dRldbvK49x2Z22kO2nkZZOnmQDzYFV4+yGSbaHdjT/SDTmgOqMRKcxe7l3n3KaKfyNS5yW6Rup+2W5KMYuzdM3uTCp0o+SBMnAeanuG4AkSr3nBTDIV3k4RpViM96e799aRGV+IrW3vQnF50UG8IgCi9R2NCGOZWIju3XMGc=,iv:MOvikYGCdRJN0eLk8YmezYJN6i/Qfx+S9huKZSXRkbw=,tag:7EGI9AF4OlSnUsImEdQ2Rw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
