apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1So6gkaJYzpo0T1cfETK3FLhy10WpmxBog+3ib1ulcXZro/fuNc3rfEqTm2Nyl2EbiK3+7kpSMyS+4/rB1p7sDSOHPstOJ8xAhwatJ0il6jCBOkIF+N90vPZ2Es4TbrNX4NxHG34GHv5BriZNbjGubC4yvzuA0qvBw9z0M88QqDBrgC6IJy94wUlTXIfB25b3MlMjbTnRQdlyQBZsUyfWm4AEESRNGNLQT9NtzVTFp5pox0t+YU4GxNNVLaJJ+sMn92jzkEQqxUjMX9xxmXU+fXcVaK5yV+KeZEBiFAsSsJdL/MKHW4EjYVa/SObWrG8pbUuTkaUZgrDYBoyN8UatTqg6ptT/nFE/KmZ1MH/uuwETs5VEI5JFQlOorFHqjt9,iv:qYEIjm0C6zokmfbjg49uyHpE5miHXQBtw4gxVjTuJ8g=,tag:L0MfsRP8NzdQbDo6lLCw0Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:uZESdB5AhBIsWjY6zgujK8KncTBPxIGT4heizmqB7D3pR7bykA31zZWdGoRM2V52GzedT+6JcoQA/Mu3nz8VADkBwWkgdpik7oSwe+clDN/j9GrJnobE5dkACi+34jPH17MDGegwTEiOJxjRQfMSAgDOUTPEfTycxSvH7NTs90S4Aw/4xc5UxeLlTWzT01V4BLDsgUbYfMQiaKoyt1xGcSassRlYV7VwKOhBW0InCivEUskwRZTC6RogWyUKyt5KO7DykH8i8MpUhEYHqA==,iv:hmvL6WHF4ph8TGHhIUUiIkJWKlqzbb5jI8o7t7Vssq8=,tag:mj5/RKtyUtxUPI1+WJ62aQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:I47QV4xrBid2Ri9xVSs6gcIji66yf4pQCdPaLEx8qttyTm2zF7CD9RW5k2RgadUhf8IJHv2AV7OIK2RKY+uy/GSsRZcnhoNQJxY8Jn2fsNTJVL38Pr5hLG1ZOBzV7nm1q8Aii2KWRZDwfDgC1AXAa6DQONbZGPv3f4NTrOvfZ2/DbpVOFYCbzr/V0pwSZU+7UwRzB28w6LEU9o9TrMxfVfo9EE4i2Ak1P4kw,iv:6MSnwhOo1zlKYsS8iunxJaOrxZF0/0CpGaor2xs3swE=,tag:8vUp08xSc2ewNLIUHnz24g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dj5huxfpjvhylmxlr6pw2gd826l90ww2sl2jnm30erdvruuchvdqu2j3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucTRnaDN5a0luZUVjMThz
            OG95Z2tzaGJaT0tMSmJmcGUyKzlsZzVPZUEwCkhaampzQldINlJvbE50NEozMitS
            dWFUWGZuSHk4SER6MTIrTVhWb2FtbGsKLS0tIG1KS1Vnd01aV0tmRjM4NEdWU0lj
            UHFxSjM2eHVkZERFODMzRWloWDJoMFkKnC+J+ixA9TL9XEIDWTYt+o7caJwxRv6C
            fwqNwv2rAcN21APxLtNpDop0Ef2KJ+VXJ3N13O+aoPENTPPNL66Qfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T22:48:29Z"
    mac: ENC[AES256_GCM,data:nQrRbvtetaYZg9r1B4jSFCMYXgQwpx71iEdRxHGGQC0USN95J71P/aqd8JO8oVMeuTlNIS1D/9ZL73XWmfKscnwr+gf1WXFxoX2r47CQ5MEk6vIYATFMvTrWTwkq1L+UAk5qGKA2RIVvcOXvSwHxZn5+0WAJnnLo+ugjjV24E8U=,iv:SuoRSIwM6/E1gKyB9B/e7Wnrj++UkfU+LQfFw/w99vU=,tag:peROZjhgqD28JmU9rX1Flw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
