---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
  namespace: media
spec:
  storageClassName: media-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.175
    path: "/mnt/hdd_rz2/media"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media
spec:
  storageClassName: media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
